# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gossl < Formula
  desc "simple CLI app for checking SSL certificates"
  homepage "https://vvrnv.dev"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vvrnv/gossl/releases/download/v0.2.0/gossl_0.2.0_Darwin_x86_64.tar.gz"
      sha256 "e3576f952f3fc91e6893ccbedbf07a663cc9d2581e39bf25028e2763a0ea43de"

      def install
        bin.install "gossl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vvrnv/gossl/releases/download/v0.2.0/gossl_0.2.0_Darwin_arm64.tar.gz"
      sha256 "bb2af8f6891b20c58458926e8550ed60d5aa38a468058de19f36c3d2a0fc9104"

      def install
        bin.install "gossl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vvrnv/gossl/releases/download/v0.2.0/gossl_0.2.0_Linux_arm64.tar.gz"
      sha256 "10d4fa51a67a3013e6f0245bc76c9df048fdf669b6e1d4fe348cbf08c0bc3fe6"

      def install
        bin.install "gossl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/vvrnv/gossl/releases/download/v0.2.0/gossl_0.2.0_Linux_x86_64.tar.gz"
      sha256 "53e5525246e36d341f9fd64227b8e937cd5aa2b3ca10ba3b58b7c94db70eae9b"

      def install
        bin.install "gossl"
      end
    end
  end
end
