# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gossl < Formula
  desc "simple CLI app for checking SSL certificates"
  homepage "https://vvrnv.dev"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vvrnv/gossl/releases/download/v0.2.1/gossl_0.2.1_Darwin_x86_64.tar.gz"
      sha256 "d1067fd22d7a5592a5054797d9b0f62233353538c82201e80dd010fe24fc092d"

      def install
        bin.install "gossl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vvrnv/gossl/releases/download/v0.2.1/gossl_0.2.1_Darwin_arm64.tar.gz"
      sha256 "9a4bb9534d256d9b1b7e14a615155b75de948a1b1a6496ad239e5cad23fc40fe"

      def install
        bin.install "gossl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vvrnv/gossl/releases/download/v0.2.1/gossl_0.2.1_Linux_arm64.tar.gz"
      sha256 "62e426ac0d9688f41c2b0af872ebbba9d625363af35db2835269a7ff30664123"

      def install
        bin.install "gossl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/vvrnv/gossl/releases/download/v0.2.1/gossl_0.2.1_Linux_x86_64.tar.gz"
      sha256 "df787229df942c3be36af2ab3c976bab00f8fecde4b9d7480eee974b5ed78fb6"

      def install
        bin.install "gossl"
      end
    end
  end
end
