# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gossl < Formula
  desc "simple CLI app for checking SSL certificates"
  homepage "https://vvrnv.dev"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vvrnv/gossl/releases/download/v0.5.0/gossl_0.5.0_darwin_amd64.tar.gz"
      sha256 "7f18d1faf921215920836942b7e4e13b54282b8ec838c118fbb6d841258afd23"

      def install
        bin.install "gossl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vvrnv/gossl/releases/download/v0.5.0/gossl_0.5.0_darwin_arm64.tar.gz"
      sha256 "714571c2ac2b157482fb26e715f61df68b1fff7073f19b6a2b9527770eb4e9eb"

      def install
        bin.install "gossl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vvrnv/gossl/releases/download/v0.5.0/gossl_0.5.0_linux_arm64.tar.gz"
      sha256 "5cfbc9bf8b7edf07b66ab03b32da504e7d91109498b17013ff6835bcb85803d9"

      def install
        bin.install "gossl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/vvrnv/gossl/releases/download/v0.5.0/gossl_0.5.0_linux_amd64.tar.gz"
      sha256 "05a52c39f6f11bf5a028e176c25c09b9397eb759123ded0f3b1bf97d00f68cb4"

      def install
        bin.install "gossl"
      end
    end
  end
end
