# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ingpoint < Formula
  desc "app to get all unique ingress hosts for current kubernetes context"
  homepage "https://vvrnv.dev"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/vvrnv/ingpoint/releases/download/v0.2.0/ingpoint_0.2.0_darwin_arm64.tar.gz"
      sha256 "9a853ff99567d99ff3db04353a380fa6b020a6cc4e8d388593a0f448bec0d4f7"

      def install
        bin.install "ingpoint"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/vvrnv/ingpoint/releases/download/v0.2.0/ingpoint_0.2.0_darwin_amd64.tar.gz"
      sha256 "2f64c0d6c634eba75cb8ca29021c83730c629ac8828b7164dcde3ec4a4767ebd"

      def install
        bin.install "ingpoint"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vvrnv/ingpoint/releases/download/v0.2.0/ingpoint_0.2.0_linux_arm64.tar.gz"
      sha256 "dd0575c7ade78603bf66f5093634f17e7d56a4237f31d13da00207d4e9089126"

      def install
        bin.install "ingpoint"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/vvrnv/ingpoint/releases/download/v0.2.0/ingpoint_0.2.0_linux_amd64.tar.gz"
      sha256 "a0405e4ae4b1393d3aaba973dc8bb8214320d98a9ec503c420c0851b878b01bd"

      def install
        bin.install "ingpoint"
      end
    end
  end
end
