# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ingpoint < Formula
  desc "app to get all unique ingress hosts for current kubernetes context"
  homepage "https://vvrnv.dev"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/vvrnv/ingpoint/releases/download/v0.2.1/ingpoint_0.2.1_darwin_arm64.tar.gz"
      sha256 "715a181a4f3bb412ef17158100b91e96ad6055a13a88a925f5eccc6b45b6c720"

      def install
        bin.install "ingpoint"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/vvrnv/ingpoint/releases/download/v0.2.1/ingpoint_0.2.1_darwin_amd64.tar.gz"
      sha256 "a9561fbd84fd5da5f7137a8b4b9ffbfb16e4241eceedd895433a63509f590743"

      def install
        bin.install "ingpoint"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vvrnv/ingpoint/releases/download/v0.2.1/ingpoint_0.2.1_linux_arm64.tar.gz"
      sha256 "919fce8bee9e16ec099ec5aa40a8a5317d5fd2de5a6757e72eebd0afee173d12"

      def install
        bin.install "ingpoint"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/vvrnv/ingpoint/releases/download/v0.2.1/ingpoint_0.2.1_linux_amd64.tar.gz"
      sha256 "31c8e7118bb11a69c5450d3e5d087325ff16a6850cfee2900f4a5befefa0c3fb"

      def install
        bin.install "ingpoint"
      end
    end
  end
end
