# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kctxsync < Formula
  desc "A command-line tool to sync certificate and key data from a remote Kubernetes cluster's kubeconfig to your local kubeconfig."
  homepage "https://vvrnv.dev"
  version "0.2.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/vvrnv/kctxsync/releases/download/v0.2.1/kctxsync_0.2.1_darwin_amd64.tar.gz"
      sha256 "1e97aed2b26e8ec3bae6ebd98c2623980f0267ab91c7bdd36f58359ddf809fc4"

      def install
        bin.install "kctxsync"
      end
    end
    on_arm do
      url "https://github.com/vvrnv/kctxsync/releases/download/v0.2.1/kctxsync_0.2.1_darwin_arm64.tar.gz"
      sha256 "f51b70d8b3592468dfb74d88f79bad5ffa5113a6e1eeca92b03bb8c002cbcf14"

      def install
        bin.install "kctxsync"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/vvrnv/kctxsync/releases/download/v0.2.1/kctxsync_0.2.1_linux_amd64.tar.gz"
        sha256 "44d0ee7b1d1fc94c2ac8566851fdc46e7bbb755563fcca2264ea55a0835497f1"

        def install
          bin.install "kctxsync"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/vvrnv/kctxsync/releases/download/v0.2.1/kctxsync_0.2.1_linux_arm64.tar.gz"
        sha256 "d65ac3cb733900451cd91a1f27275ae625444e151a273745ae24df19b5227f23"

        def install
          bin.install "kctxsync"
        end
      end
    end
  end
end
